<a href="https://colab.research.google.com/github/MYTHILY7/Data-Analysis-and-Visualization-/blob/main/Covid_dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install pandas

In [ ]:
import pandas as pd

In [ ]:
covid=pd.read_csv("/content/drive/MyDrive/covid dataset.csv")

In [ ]:
covid.shape

(187, 15)

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
covid.head()

Country/Region  Confirmed  ...  1 week % increase             WHO Region
0    Afghanistan      36263  ...               2.07  Eastern Mediterranean
1        Albania       4880  ...              17.00                 Europe
2        Algeria      27973  ...              18.07                 Africa
3        Andorra        907  ...               2.60                 Europe
4         Angola        950  ...              26.84                 Africa

[5 rows x 15 columns]

In [ ]:
covid=pd.read_csv("/content/drive/MyDrive/covid dataset.csv",index_col=0)
covid.head()

Confirmed  Deaths  ...  1 week % increase             WHO Region
Country/Region                     ...                                          
Afghanistan         36263    1269  ...               2.07  Eastern Mediterranean
Albania              4880     144  ...              17.00                 Europe
Algeria             27973    1163  ...              18.07                 Africa
Andorra               907      52  ...               2.60                 Europe
Angola                950      41  ...              26.84                 Africa

[5 rows x 14 columns]

In [ ]:
import pandas as pd
covid=pd.read_csv("/content/drive/MyDrive/covid dataset.csv")
pd.set_option("max_rows",69)

In [ ]:
import pandas as pd
covid=pd.read_csv("/content/drive/MyDrive/covid dataset.csv")
covid['Recovered']

0      25198
1       2745
2      18837
3        803
4        242
       ...  
182     3752
183        8
184      833
185     2815
186      542
Name: Recovered, Length: 187, dtype: int64

In [ ]:
covid['New deaths']

0      10
1       6
2       8
3       0
4       1
       ..
182     2
183     0
184     4
185     1
186     2
Name: New deaths, Length: 187, dtype: int64

In [ ]:
covid.iloc[0]

Country/Region                      Afghanistan
Confirmed                                 36263
Deaths                                     1269
Recovered                                 25198
Active                                     9796
New cases                                   106
New deaths                                   10
New recovered                                18
Deaths / 100 Cases                          3.5
Recovered / 100 Cases                     69.49
Deaths / 100 Recovered                     5.04
Confirmed last week                       35526
1 week change                               737
1 week % increase                          2.07
WHO Region                Eastern Mediterranean
Name: 0, dtype: object

In [ ]:
covid.iloc[:, 0]

0             Afghanistan
1                 Albania
2                 Algeria
3                 Andorra
4                  Angola
              ...        
182    West Bank and Gaza
183        Western Sahara
184                 Yemen
185                Zambia
186              Zimbabwe
Name: Country/Region, Length: 187, dtype: object

In [ ]:
covid.iloc[:10,  0]

0            Afghanistan
1                Albania
2                Algeria
3                Andorra
4                 Angola
5    Antigua and Barbuda
6              Argentina
7                Armenia
8              Australia
9                Austria
Name: Country/Region, dtype: object

In [ ]:
covid.iloc[2:10,0]

2                Algeria
3                Andorra
4                 Angola
5    Antigua and Barbuda
6              Argentina
7                Armenia
8              Australia
9                Austria
Name: Country/Region, dtype: object

In [ ]:
covid.iloc[-7]

Country/Region            Venezuela
Confirmed                     15988
Deaths                          146
Recovered                      9959
Active                         5883
New cases                       525
New deaths                        4
New recovered                   213
Deaths / 100 Cases             0.91
Recovered / 100 Cases         62.29
Deaths / 100 Recovered         1.47
Confirmed last week           12334
1 week change                  3654
1 week % increase             29.63
WHO Region                 Americas
Name: 180, dtype: object

In [ ]:
covid.loc[3,'Confirmed']

907

In [ ]:
covid.loc[:,['Confirmed','Deaths','Recovered']]

Confirmed  Deaths  Recovered
0        36263    1269      25198
1         4880     144       2745
2        27973    1163      18837
3          907      52        803
4          950      41        242
..         ...     ...        ...
182      10621      78       3752
183         10       1          8
184       1691     483        833
185       4552     140       2815
186       2704      36        542

[187 rows x 3 columns]

In [ ]:
covid.set_index('Deaths')

Country/Region  Confirmed  ...  1 week % increase             WHO Region
Deaths                                 ...                                          
1269           Afghanistan      36263  ...               2.07  Eastern Mediterranean
144                Albania       4880  ...              17.00                 Europe
1163               Algeria      27973  ...              18.07                 Africa
52                 Andorra        907  ...               2.60                 Europe
41                  Angola        950  ...              26.84                 Africa
...                    ...        ...  ...                ...                    ...
78      West Bank and Gaza      10621  ...              19.12  Eastern Mediterranean
1           Western Sahara         10  ...               0.00                 Africa
483                  Yemen       1691  ...               4.45  Eastern Mediterranean
140                 Zambia       4552  ...              36.86                 Africa
36                Zimbabwe       2704  ...              57.85                 Africa

[187 rows x 14 columns]

In [ ]:
covid.Recovered ==25198

0       True
1      False
2      False
3      False
4      False
       ...  
182    False
183    False
184    False
185    False
186    False
Name: Recovered, Length: 187, dtype: bool

In [ ]:
covid.loc[(covid.Recovered ==25198) & (covid.Active >= 90)]

Country/Region  Confirmed  ...  1 week % increase             WHO Region
0    Afghanistan      36263  ...               2.07  Eastern Mediterranean

[1 rows x 15 columns]

In [ ]:
covid.loc[(covid.Recovered ==25198) | (covid.Active >= 90)]

Country/Region  Confirmed  ...  1 week % increase             WHO Region
0           Afghanistan      36263  ...               2.07  Eastern Mediterranean
1               Albania       4880  ...              17.00                 Europe
2               Algeria      27973  ...              18.07                 Africa
4                Angola        950  ...              26.84                 Africa
6             Argentina     167416  ...              28.02               Americas
..                  ...        ...  ...                ...                    ...
180           Venezuela      15988  ...              29.63               Americas
182  West Bank and Gaza      10621  ...              19.12  Eastern Mediterranean
184               Yemen       1691  ...               4.45  Eastern Mediterranean
185              Zambia       4552  ...              36.86                 Africa
186            Zimbabwe       2704  ...              57.85                 Africa

[148 rows x 15 columns]

In [ ]:
covid.loc[covid.Recovered.isin(['Yemen', 'Zambia'])]

Empty DataFrame
Columns: [Country/Region, Confirmed, Deaths, Recovered, Active, New cases, New deaths, New recovered, Deaths / 100 Cases, Recovered / 100 Cases, Deaths / 100 Recovered, Confirmed last week, 1 week change, 1 week % increase, WHO Region]
Index: []

In [ ]:
covid.loc[covid.Recovered.notnull()]

Country/Region  Confirmed  ...  1 week % increase             WHO Region
0           Afghanistan      36263  ...               2.07  Eastern Mediterranean
1               Albania       4880  ...              17.00                 Europe
2               Algeria      27973  ...              18.07                 Africa
3               Andorra        907  ...               2.60                 Europe
4                Angola        950  ...              26.84                 Africa
..                  ...        ...  ...                ...                    ...
182  West Bank and Gaza      10621  ...              19.12  Eastern Mediterranean
183      Western Sahara         10  ...               0.00                 Africa
184               Yemen       1691  ...               4.45  Eastern Mediterranean
185              Zambia       4552  ...              36.86                 Africa
186            Zimbabwe       2704  ...              57.85                 Africa

[187 rows x 15 columns]

In [ ]:
import numpy as np



In [ ]:
covid= np.arange(15).reshape(3, 5)
covid

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
covid.shape

(3, 5)

In [ ]:
covid.ndim

2

In [ ]:
covid.itemsize

8

In [ ]:
type(covid)

numpy.ndarray

In [ ]:
covid.dtype

dtype('int64')

In [ ]:
np.ones( (2,3,4), dtype=np.int16 )

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [ ]:
covid= np.array( [ [434,76], [23,963] ], dtype=complex )
covid

array([[434.+0.j,  76.+0.j],
       [ 23.+0.j, 963.+0.j]])

In [ ]:
np.ones( (2,3,4), dtype=np.int16 )

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [ ]:
np.arange( 10, 30, 5 )

array([10, 15, 20, 25])