<a href="https://colab.research.google.com/github/MYTHILY7/Data-Analysis-and-Visualization-/blob/main/day4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

UNDERSTANDING NUMERICAL COMPUTING USING PYTHON - NUMPY

In [ ]:
import numpy
x=numpy.array([[1,2,3,4],[5,6,7,9]])
print(x.shape)

(2, 4)


In [ ]:
import numpy as np
x=np.array([[1,2,3,4],[5,6,7,9]])
print(x.shape)
x.shape=(4,2)
print(x)

(2, 4)
[[1 2]
 [3 4]
 [5 6]
 [7 9]]


In [ ]:
import numpy as np

user_input = input("Enter the elements of the array separated by space: ")
array_list = [float(i) for i in user_input.split()]

user_array = np.array(array_list)

size = user_array.size

print(f"The size of the array is: {size}")


Enter the elements of the array separated by space: 5 7 8 3
The size of the array is: 4


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

mask = arr > 5
print(mask)

selected_values = arr[mask]
print(selected_values)

mask = (arr > 5) & (arr < 9)
print(arr[mask])

mask = (arr < 3) | (arr > 7)
print(arr[mask])

[False False False False False  True  True  True  True]
[6 7 8 9]
[6 7 8]
[1 2 8 9]


In [ ]:
y=x[2]
print(y)

[5 6]


SLICING

In [ ]:
import numpy as np
x=np.arange(20)
y=slice(3,9,2)
print(x[y])

[3 5 7]


INTEGER INDEXING

In [ ]:
x=np.array([[1,2],[3,4],[5,6]])
y=x[[0,1,2],[0,1,0]]
print (y)

[1 4 5]


TRIGNOMETRIC

In [ ]:
import numpy as np

arr = np.array([90, 180, 270, 360])

x = np.deg2rad(arr)

print(x)

[1.57079633 3.14159265 4.71238898 6.28318531]


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print('Sine of angles:')
print(np.sin(x*np.pi/180))
print('\n')
print('cosine values')
print(np.cos(x*np.pi/180))
print('\n')
print('Tangent values')
print(np.tan(x*np.pi/180))

Sine of angles:
[0.02741213 0.05480367 0.08215401 0.10944261]


cosine values
[0.99962422 0.99849715 0.99661965 0.99399312]


Tangent values
[0.02742244 0.05488615 0.08243266 0.11010399]


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[2] + arr[3])

7


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[4:])

[5 6 7]


ARITHMETIC OPERATIONS

In [ ]:
import numpy as np
x=np.arange(9,dtype=np.float).reshape(3,3)
print('First array:')
print(x)
print('\n')
print('Second array:')
y=np.array([20,20,20])
print(y)
z=np.add(x,y)
print(z)
print('\n')
print(np.add(x,y))
print('\n')
print(np.subtract(x,y))
print('\n')
print(np.multiply(x,y))
print('\n')
print(np.divide(x,y))

First array:
[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]


Second array:
[20 20 20]
[[20. 21. 22.]
 [23. 24. 25.]
 [26. 27. 28.]]


[[20. 21. 22.]
 [23. 24. 25.]
 [26. 27. 28.]]


[[-20. -19. -18.]
 [-17. -16. -15.]
 [-14. -13. -12.]]


[[  0.  20.  40.]
 [ 60.  80. 100.]
 [120. 140. 160.]]


[[0.   0.05 0.1 ]
 [0.15 0.2  0.25]
 [0.3  0.35 0.4 ]]


<ipython-input-13-79172d5ed2a5>:2: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  x=np.arange(9,dtype=np.float).reshape(3,3)
